print('Введите значение a=')
a=float(input())
print('Введите значение b=')
b=float(input())
print('Введите значение c=')
c=float(input())
print('Введите значение d=')
d=float(input())
print(((-3+a**2)*b-2**3)/c-2*d)